// ─── Seed data for the in-memory store ───────────────────────────
// Mirrors the original static data plus admin user + demo records.

import { randomUUID } from 'crypto';

const now = Date.now();
const dayMs = 86_400_000;

export const seedData = {
  // ─── Catalog ──────────────────────────────────────────────────
  products: [
    {
      id: 'demo-product-1',
      name: 'Demo Product 1 - Multivitamin Complex 60s',
      shortName: 'Multivitamin Complex',
      brand: 'MediPharma',
      price: 24.99,
      oldPrice: 118,
      note: '60 Capsules',
      icon: 'medication',
      tint: '#d9eeee',
      badge: '15% OFF',
      categoryId: 'cat-vitamins',
      stock: 245,
      reorderLevel: 50,
      sku: 'MED-001',
      status: 'active',
      description: 'A complete daily multivitamin complex with 23 essential vitamins and minerals to support overall health, immunity, and energy levels.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-2',
      name: 'Ashwagandha Extract 500mg 60 Caps',
      shortName: 'Ashwagandha Extract',
      brand: 'Naturals',
      price: 18.5,
      note: '500mg, 90 Tablets',
      icon: 'spa',
      tint: '#e7f0df',
      categoryId: 'cat-ayurveda',
      stock: 18,
      reorderLevel: 30,
      sku: 'MED-014',
      status: 'active',
      description: 'Pure Ashwagandha root extract for stress relief, better sleep, and improved cognitive function. Standardized to 5% withanolides.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-3',
      name: 'Advanced Blood Glucose Monitor Kit',
      shortName: 'Blood Glucose Monitor',
      brand: 'GlucoCare',
      price: 39.99,
      note: 'Complete monitoring kit',
      icon: 'monitor_heart',
      tint: '#dcecf4',
      badge: 'BESTSELLER',
      categoryId: 'cat-healthcare',
      stock: 0,
      reorderLevel: 20,
      sku: 'MED-028',
      status: 'active',
      description: 'Complete blood glucose monitoring kit with meter, 50 test strips, lancets, and carrying case. Results in 5 seconds.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-4',
      name: 'Fast Acting Muscle Relief Gel 50g',
      shortName: 'Muscle Relief Gel',
      brand: 'ReliefPlus',
      price: 14.5,
      note: '50g tube',
      icon: 'healing',
      tint: '#f2e4d7',
      categoryId: 'cat-healthcare',
      stock: 82,
      reorderLevel: 25,
      sku: 'MED-042',
      status: 'active',
      description: 'Fast-acting topical gel for muscle and joint pain relief. Contains menthol and methyl salicylate for soothing cool-warm therapy.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-5',
      name: 'Vitamin D3 5000 IU Softgels 120ct',
      shortName: 'Vitamin D3 5000 IU',
      brand: 'HealthKart',
      price: 12.99,
      oldPrice: 19.99,
      note: '120 Softgels',
      icon: 'pill',
      tint: '#fef3c7',
      categoryId: 'cat-vitamins',
      stock: 320,
      reorderLevel: 60,
      sku: 'MED-055',
      status: 'active',
      description: 'High potency Vitamin D3 supplement for bone health, immune support, and mood regulation. Daily dose supports calcium absorption.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-6',
      name: 'Omeprazole 20mg Delayed Release 42ct',
      shortName: 'Omeprazole 20mg',
      brand: 'MediPharma',
      price: 22.5,
      note: '42 Tablets',
      icon: 'medication',
      tint: '#fee2e2',
      badge: 'PRESCRIPTION',
      categoryId: 'cat-prescription',
      stock: 95,
      reorderLevel: 30,
      sku: 'MED-070',
      status: 'active',
      description: 'Prescription medication for frequent heartburn. Taken once daily for 14 days. Requires valid prescription.',
      prescriptionRequired: true,
    },
    {
      id: 'demo-product-7',
      name: 'Digital Thermometer Forehead IR',
      shortName: 'IR Thermometer',
      brand: 'GlucoCare',
      price: 29.99,
      note: 'Non-contact',
      icon: 'thermostat',
      tint: '#dbeafe',
      categoryId: 'cat-healthcare',
      stock: 45,
      reorderLevel: 15,
      sku: 'MED-088',
      status: 'active',
      description: 'Professional-grade infrared forehead thermometer with 1-second reading, fever alarm, and memory for 32 readings.',
      prescriptionRequired: false,
    },
    {
      id: 'demo-product-8',
      name: 'Hand Sanitizer Gel 500ml Aloe',
      shortName: 'Hand Sanitizer 500ml',
      brand: 'ReliefPlus',
      price: 6.99,
      note: '500ml with Aloe',
      icon: 'sanitizer',
      tint: '#dcfce7',
      badge: 'VALUE',
      categoryId: 'cat-winter-care',
      stock: 540,
      reorderLevel: 100,
      sku: 'MED-100',
      status: 'active',
      description: '70% alcohol-based hand sanitizer with moisturizing aloe vera. Kills 99.9% of germs without drying skin.',
      prescriptionRequired: false,
    },
  ],

  // ─── Categories ───────────────────────────────────────────────
  categories: [
    { id: 'cat-prescription', name: 'Prescription Meds', icon: 'medication', tint: '#fee2e2', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-vitamins', name: 'Vitamins & Supplements', icon: 'pill', tint: '#f3e5f5', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-ayurveda', name: 'Ayurveda', icon: 'spa', tint: '#f1f8e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-homeopathy', name: 'Homeopathy', icon: 'medication', tint: '#e8f5e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-healthcare', name: 'Healthcare Devices', icon: 'monitor_heart', tint: '#e1f5fe', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-sexual-wellness', name: 'Sexual Wellness', icon: 'favorite', tint: '#fff3e0', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-winter-care', name: 'Winter Care', icon: 'ac_unit', tint: '#e0f7fa', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-diabetes', name: 'Diabetes Care', icon: 'bloodtype', tint: '#fff8e1', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-skin-care', name: 'Skin Care', icon: 'face', tint: '#f1f8e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-elderly-care', name: 'Elderly Care', icon: 'elderly', tint: '#fff3e0', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-supplements', name: 'Supplements', icon: 'fitness_center', tint: '#ffe0b2', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-health-food', name: 'Health Food', icon: 'nutrition', tint: '#fbe9e7', productCount: 0, visibility: 'active', updatedAt: now },
  ],

  // ─── Health Concerns ──────────────────────────────────────────
  healthConcerns: [
    { id: 'hc-1', name: 'Diabetes care', icon: 'bloodtype', tint: '#eadff3' },
    { id: 'hc-2', name: 'Cardiac care', icon: 'favorite', tint: '#f6dfe4' },
    { id: 'hc-3', name: 'Pain relief', icon: 'healing', tint: '#dcecf4' },
    { id: 'hc-4', name: 'Kidney care', icon: 'kidney', tint: '#f6e4d6' },
    { id: 'hc-5', name: 'Muscle care', icon: 'fitness_center', tint: '#d9eeee' },
    { id: 'hc-6', name: 'Liver care', icon: 'medical_information', tint: '#f2d9d9' },
    { id: 'hc-7', name: 'Respiratory care', icon: 'air', tint: '#dbeafe' },
    { id: 'hc-8', name: 'Eye care', icon: 'visibility', tint: '#fef3c7' },
    { id: 'hc-9', name: 'Mental Wellness', icon: 'psychology', tint: '#ede9fe' },
  ],

  // ─── Brands ───────────────────────────────────────────────────
  brands: [
    { id: 'b1', name: 'Himalaya', logo: '', visibility: 'active' },
    { id: 'b2', name: 'Horlicks', logo: '', visibility: 'active' },
    { id: 'b3', name: 'Dabur', logo: '', visibility: 'active' },
    { id: 'b4', name: 'Dr. Morepen', logo: '', visibility: 'active' },
    { id: 'b5', name: 'MB', logo: '', visibility: 'active' },
    { id: 'b6', name: 'Bourn Vita', logo: '', visibility: 'active' },
    { id: 'b7', name: 'mamaearth', logo: '', visibility: 'active' },
    { id: 'b8', name: 'JIVA', logo: '', visibility: 'active' },
    { id: 'b9', name: 'HealthKart', logo: '', visibility: 'active' },
  ],

  // ─── Offers ───────────────────────────────────────────────────
  offers: [
    { id: 'o1', text: 'Flat 25% off + up to $10 cashback', code: 'MEDI25', visibility: 'active' },
    { id: 'o2', text: 'Free delivery on orders above $50', code: 'FREE50', visibility: 'active' },
    { id: 'o3', text: 'Buy 2 Get 1 Free on Vitamins', code: 'B2G1', visibility: 'active' },
  ],

  // ─── Home banners (controlled from admin) ─────────────────────
  banners: [
    { id: 'banner-hero', slot: 'hero', title: 'Boost your immunity', subtitle: 'Health essentials for brighter days.', ctaText: 'CLICK TO SHOP', ctaHref: '/products', badge: 'Everyday wellness', visibility: 'active' },
    { id: 'banner-prescription', slot: 'prescription', title: 'Order with prescription', subtitle: 'Upload a prescription and tell us what you need. We do the rest!', ctaText: 'Order Now', ctaHref: '/prescriptions', note: 'Flat 25% off on medicines*', visibility: 'active' },
    { id: 'banner-essentials', slot: 'essentials', title: 'Essentials', subtitle: 'Daily health', ctaText: 'SHOP NOW', ctaHref: '/products', note: 'UP TO 30% off', visibility: 'active' },
    { id: 'banner-call', slot: 'call', title: 'Call to order medicines', subtitle: 'Need medicine without any hassle? call us now', ctaText: 'Call Now', ctaHref: '', visibility: 'active' },
  ],

  // ─── Lab packages & tests ─────────────────────────────────────
  labPackages: [
    { id: 'full-body-checkup', name: 'Full Body Checkup', detail: 'Includes 85 tests: CBC, Thyroid, Lipid, Liver & more.', price: 149, icon: 'favorite', badge: '50% OFF', visibility: 'active' },
    { id: 'cardiac-profile', name: 'Cardiac Profile', detail: 'Complete heart health evaluation and lipid panel.', price: 89, icon: 'ecg_heart', visibility: 'active' },
    { id: 'womens-health', name: "Women's Health", detail: 'Essential screening including Iron, Thyroid, Vitamin D.', price: 120, icon: 'woman', visibility: 'active' },
    { id: 'diabetic-screening', name: 'Diabetic Screening', detail: 'HbA1c, Fasting Sugar, and vital organ screening.', price: 45, icon: 'bloodtype', badge: 'Popular', visibility: 'active' },
  ],
  labTests: [
    { id: 'lt1', name: 'Complete Blood Count (CBC)', detail: 'Results in 24 hrs', price: 15, visibility: 'active' },
    { id: 'lt2', name: 'Thyroid Profile (T3, T4, TSH)', detail: 'Results in 24 hrs', price: 25, visibility: 'active' },
    { id: 'lt3', name: 'Lipid Profile', detail: 'Fasting required', price: 20, visibility: 'active' },
    { id: 'lt4', name: 'Vitamin D Test', detail: 'Results in 48 hrs', price: 35, visibility: 'active' },
    { id: 'lt5', name: 'HbA1c Diabetes Test', detail: 'No fasting required', price: 28, visibility: 'active' },
  ],

  // ─── Demo orders (visible to admin) ───────────────────────────
  orders: [
    {
      id: 'MD-8492-X',
      userId: 'u1',
      customerName: 'Health User',
      customerEmail: 'user@medidemo.com',
      items: [{ productId: 'demo-product-1', name: 'Multivitamin Complex', qty: 3, price: 24.99 }],
      total: 142.50,
      shippingAddress: '123 Wellness Avenue',
      status: 'Delivered',
      type: 'medicine',
      prescriptionVerified: true,
      createdAt: now - dayMs * 2,
    },
    {
      id: 'MD-8498-K',
      userId: 'u2',
      customerName: 'Ava Morgan',
      customerEmail: 'ava@example.com',
      items: [{ name: 'Full Body Checkup', qty: 1, price: 149 }],
      total: 149.00,
      shippingAddress: '48 Park Lane',
      status: 'Processing',
      type: 'lab',
      prescriptionVerified: false,
      createdAt: now - dayMs,
    },
    {
      id: 'MD-8501-Q',
      userId: 'u3',
      customerName: 'Marcus Chen',
      customerEmail: 'marcus@example.com',
      items: [
        { productId: 'demo-product-5', name: 'Vitamin D3 5000 IU', qty: 1, price: 12.99 },
        { productId: 'demo-product-1', name: 'Multivitamin Complex', qty: 1, price: 24.99 },
      ],
      total: 37.98,
      shippingAddress: '78 Healthway Ave',
      status: 'In Transit',
      type: 'medicine',
      prescriptionVerified: false,
      createdAt: now - 36_00_000,
    },
    {
      id: 'MD-8508-P',
      userId: 'u4',
      customerName: 'Elena Stone',
      customerEmail: 'elena@example.com',
      items: [{ productId: 'demo-product-3', name: 'Blood Glucose Monitor', qty: 1, price: 39.99 }],
      total: 64.50,
      shippingAddress: '90 Madison Street',
      status: 'Cancelled',
      type: 'medicine',
      prescriptionVerified: false,
      createdAt: now - dayMs * 3,
    },
    {
      id: 'LB-1001',
      userId: 'u1',
      customerName: 'Health User',
      customerEmail: 'user@medidemo.com',
      items: [{ name: 'Full Body Checkup', qty: 1, price: 149 }],
      total: 149.00,
      shippingAddress: '123 Wellness Avenue',
      status: 'Confirmed',
      type: 'lab',
      scheduledAt: now + dayMs,
      prescriptionVerified: false,
      createdAt: now - 7200_000,
    },
    {
      id: 'LB-1002',
      userId: 'u2',
      customerName: 'Ava Morgan',
      customerEmail: 'ava@example.com',
      items: [{ name: 'Thyroid Profile', qty: 1, price: 25 }],
      total: 25.00,
      shippingAddress: '48 Park Lane',
      status: 'Processing',
      type: 'lab',
      scheduledAt: now + 36_00_000,
      prescriptionVerified: false,
      createdAt: now - 5400_000,
    },
  ],

  // ─── Demo users (customer accounts) ───────────────────────────
  users: [
    { id: 'u1', name: 'Health User', email: 'user@medidemo.com', role: 'patient', status: 'active', phone: '+1 555-0100', lastLogin: now - 36_00_000 },
    { id: 'u2', name: 'Ava Morgan', email: 'ava@example.com', role: 'patient', status: 'active', phone: '+1 555-0101', lastLogin: now - dayMs },
    { id: 'u3', name: 'Marcus Chen', email: 'marcus@example.com', role: 'patient', status: 'active', phone: '+1 555-0102', lastLogin: now - dayMs * 2 },
    { id: 'u4', name: 'Elena Stone', email: 'elena@example.com', role: 'patient', status: 'blocked', phone: '+1 555-0103', lastLogin: now - dayMs * 5 },
    { id: 'u5', name: 'David Chen', email: 'david@example.com', role: 'lab_tech', status: 'active', phone: '+1 555-0104', lastLogin: now - dayMs * 3 },
    { id: 'u6', name: 'Dr. Sarah Jenkins', email: 'sarah@example.com', role: 'doctor', status: 'active', phone: '+1 555-0105', lastLogin: now - 36_00_000 },
  ],

  // ─── Employees (staff managed by admin) ───────────────────────
  employees: [
    { id: 'e1', name: 'Sarah Jenkins', email: 'sarah@example.com', department: 'Pharmacists', status: 'active', joinedAt: '2024-01-12', phone: '+1 555-0200' },
    { id: 'e2', name: 'Michael Chang', email: 'michael@example.com', department: 'Lab Technicians', status: 'active', joinedAt: '2024-03-06', phone: '+1 555-0201' },
    { id: 'e3', name: 'David Miller', email: 'dmiller@example.com', department: 'Delivery Partners', status: 'active', joinedAt: '2024-04-21', phone: '+1 555-0202' },
    { id: 'e4', name: 'Priya Shah', email: 'priya@example.com', department: 'Admin', status: 'pending', joinedAt: '2024-06-14', phone: '+1 555-0203' },
  ],

  // ─── Support tickets ──────────────────────────────────────────
  supportTickets: [
    { id: 'SUP-2201', userId: 'u1', customerName: 'Health User', subject: 'Prescription verification', priority: 'High', status: 'Open', message: 'Need help verifying my uploaded prescription for Omeprazole.', createdAt: now - 7200_000 },
    { id: 'SUP-2202', userId: 'u2', customerName: 'Ava Morgan', subject: 'Delivery time change', priority: 'Medium', status: 'In Progress', message: 'Can my delivery be moved to tomorrow morning?', createdAt: now - dayMs },
    { id: 'SUP-2203', userId: 'u3', customerName: 'Marcus Chen', subject: 'Refund request', priority: 'High', status: 'Open', message: 'Order #MD-8508-P was cancelled. Requesting refund.', createdAt: now - dayMs * 2 },
    { id: 'SUP-2204', userId: 'u4', customerName: 'Elena Stone', subject: 'Lab report question', priority: 'Low', status: 'Pending', message: 'Question about my CBC report results.', createdAt: now - dayMs * 3 },
  ],

  // ─── Transactions (derived from orders) ───────────────────────
  transactions: [
    { id: 'TXN-78421', orderId: 'MD-8492-X', customerName: 'Health User', method: 'Visa •••• 4242', amount: 142.50, status: 'Completed', createdAt: now - dayMs * 2 },
    { id: 'TXN-78422', orderId: 'MD-8498-K', customerName: 'Ava Morgan', method: 'UPI', amount: 149.00, status: 'Completed', createdAt: now - dayMs },
    { id: 'TXN-78423', orderId: 'LB-1003', customerName: 'Marcus Chen', method: 'Wallet', amount: 25.00, status: 'Pending', createdAt: now - 36_00_000 },
    { id: 'TXN-78424', orderId: 'MD-8508-P', customerName: 'Elena Stone', method: 'Visa •••• 8801', amount: 64.50, status: 'Refunded', createdAt: now - dayMs * 3 },
  ],

  // ─── Site settings (admin controlled) ─────────────────────────
  settings: [
    { id: 'site', siteName: 'MediDemo', tagline: 'Everyday wellness', supportPhone: '+1 555-1234', supportEmail: 'support@medidemo.com', currency: 'USD', currencySymbol: '$', freeShippingThreshold: 50, prescriptionDiscountPct: 25, heroBadgeText: 'Everyday wellness', heroTitle: 'Boost your immunity', heroSubtitle: 'Health essentials for brighter days.', maintenanceMode: false },
  ],

  // ─── Auth users (for mock auth only) ──────────────────────────
  authUsers: [
    // Default admin account (email/password: admin@medidemo.com / admin123)
    {
      id: 'admin-1',
      email: 'admin@medidemo.com',
      // NOTE: in mock mode we accept any password matching the demo value.
      password: 'admin123',
      name: 'Admin User',
      role: 'admin',
      status: 'active',
    },
    {
      id: 'user-1',
      email: 'user@medidemo.com',
      password: 'user123',
      name: 'Health User',
      role: 'patient',
      status: 'active',
    },
  ],
};
